### ISSUE TITLE
Create a Static Website 

### ISSUE THREAD

**Issue by CPestanas** [telecelplay/website#1]
### **Website Link**
URL: https://telecelplay.io/

### **Action Items**

1. Please create a static landing page based from the UI in Figma Link https://www.figma.com/file/ebNCk0qNOl5gXzYLSb7UoW/TPLAY%2FDesign?node-id=2025%3A8121
2. Contents are already in the figma
3.  The website must be a **_mobile responsive_** 

### **Pending Items**

1. Contact Us form not working - removed for now
2. Social Media icons and links - to be provided

**Comment by RickGusG** [comment]
timespent*13:00 July 4, 2022 finished landing page (without implementations)

**Comment by RickGusG** [comment]
Website almost ready for launch, waiting Nuno with MailChimp and contact implemention.

**Comment by CPestanas** [comment]
The website is up here is the link https://telecelplay.io/

**Comment by CPestanas** [comment]
Hello @RickGusG ,

Kindly remove the contact us form for now as it is not working at the moment.

Thanks!

**Comment by RickGusG** [comment]
Removed contact section.

**Comment by CPestanas** [comment]
Thanks @RickGusG confirmed Contact Us Form was removed (for now).

Hi @harshadp5455  please do a quick check for the content, layout and mobile responsiveness of the page please. Please take note of the details above.


Thanks!

**Comment by harshadp5455** [comment]
timespent*00:20 {5th july 2022 Check content, layout and mobile responsiveness of the page  compare figma with website}

**Comment by RickGusG** [comment]
timespent*00:10 {july 7th changed an image and added social media links}

**Comment by harshadp5455** [comment]
timespent*00:010 {closing issue as verification and Validation Done}
Test Result : **PASSED**.
