### ISSUE TITLE
[UI] Copyrights Text adjustments at bottom of website

### ISSUE THREAD

**Issue by harshadp5455** [telecelplay/website#3]
**Describe the bug**
Copyrights Text adjustments at bottom of website

Pre Requisites : 
Website :  https://telecelplay.io/
FIGMA : https://www.figma.com/file/ebNCk0qNOl5gXzYLSb7UoW/TPLAY%2FDesign?node-id=2025%3A8121

**To Reproduce**
1. Go to bottom of website.
2. Observe copyright text and compare with figma.

**Expected behavior**
Copyrights Text should be as per design  at bottom of website

**Screenshots**
website : 
![image](https://user-images.githubusercontent.com/96113870/178237812-c33ef182-d7a8-4279-a613-36a612d9d9ed.png)

FIGMA :
![image](https://user-images.githubusercontent.com/96113870/178237771-85bfe2cf-a8e1-45fe-8e89-5e3469f46f8c.png)

**Desktop (please complete the following information):**
 - OS: android v 10
 - Browser : NA 
 - Version : WINDOWS 10 PRO

**Smartphone (please complete the following information):**
 - Device: Lava Z66
 - OS: Android 10
 - Browser : NA 
 - Version: NA

**Related US **

**Comment by harshadp5455** [comment]
timespent*00:20 {observed , discussed and raised this issue }

**Comment by RickGusG** [comment]
timespent*00:05 {adjusted letter spacing}

**Comment by RickGusG** [comment]
timespent*00:05 {lower text size in mobile view}

**Comment by harshadp5455** [comment]
timespent*00:10 {Closing issue}
Test Result : **Passed**.
**Attachment **:
![image](https://user-images.githubusercontent.com/96113870/178279034-b814b33a-a21f-457e-a7c7-5c7a7fe9e1cd.png)
