### ISSUE TITLE
[UI] Beige color spacing beside ' Soutenez le consommer local!'

### ISSUE THREAD

**Issue by harshadp5455** [telecelplay/website#4]
**Describe the bug**
Beige color spacing beside ' Soutenez le consommer local!' should be removed.

**Pre Requisites :**
Website : https://telecelplay.io/
FIGMA : https://www.figma.com/file/ebNCk0qNOl5gXzYLSb7UoW/TPLAY%2FDesign?node-id=2025%3A8121

**To Reproduce**
1. Watch  ' Soutenez le consommer local!'.
2. Observe color spacing beside image.

**Expected behavior**
Beige color spacing beside ' Soutenez le consommer local!' should be removed.

**Screenshots**
WEBSITE : 
![image](https://user-images.githubusercontent.com/96113870/178239530-7e262393-113d-4693-8488-696f74822ec6.png)

FIGMA : 
![image](https://user-images.githubusercontent.com/96113870/178239571-8a64a51e-194b-4d8b-adb4-aab6b59984ee.png)

**Desktop (please complete the following information):**
 - OS: android v 10
 - Browser : NA 
 - Version : WINDOWS 10 PRO

**Smartphone (please complete the following information):**
 - Device: Lava Z66
 - OS: Android 10
 - Browser : NA 
 - Version: NA

**Comment by harshadp5455** [comment]
timespent*00:10 {Observed and raised above issue }

**Comment by RickGusG** [comment]
timespent*00:05 {removed background color}

**Comment by harshadp5455** [comment]
timespent*00:10 {Closing issue}
Test Result : **Passed**.
**Attachment **:
![image](https://user-images.githubusercontent.com/96113870/178278558-7be73a03-e833-4aa7-aa80-e5878940861e.png)
